export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const FILTER_BY_TYPE ='FILTER_BY_TYPE';
export const GET_TYPES = "GET_TYPES";
export const FILTER_BY_STORAGE = 'FILTER_BY_STORAGE'
export const ALPHABETICAL_ORDER = 'ALPHABETICAL_ORDER';
export const SORT_BY_ATTACK = 'SORT_BY_ATTACK';
export const GET_NAME_POKEMONS = 'GET_NAME_POKEMONS';
export const CREATE_POKEMON = 'CREATE_POKEMON';